/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.SanitizationServiceRole;


import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.Organization.OrganizationDirectory;
import Business.SanitizationPerson.SanitizationPerson;
import Business.SanitizationPerson.SanitizationServiceForm;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.ServiceRequest;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author amishagupta
 */
public class SanitizationDetailsJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageEmpJPanel
     */
    private OrganizationDirectory organizationDir;
    private JPanel userProcessContainer;
    private Enterprise ent;
    private UserAccount userAccount;
    private EcoSystem system;
    private SanitizationPerson saniPerson;
    private Organization org;
    private ServiceRequest req;
    DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
       
    public SanitizationDetailsJPanel(JPanel userProcessContainer,Enterprise ent, UserAccount userAccount, EcoSystem system, Organization org, ServiceRequest req) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.organizationDir = organizationDir;
        this.userAccount = userAccount;
        this.system = system;
        this.ent=ent;
        this.org = org;
        this.req = req;
        saniPerson=org.getSaniPersonDir().findSaniPerson(userAccount.getUsername());
        populateDate();
        populateTestTable();
        addServicePanel.setVisible(false);
        saniTable.setRowHeight(25);
        saniTable.getTableHeader().setDefaultRenderer(new HeaderColor());
        
    }
     public class HeaderColor extends DefaultTableCellRenderer {
        public HeaderColor() {
            setOpaque(true);
        }
        public Component getTableCellRendererComponent(JTable table, Object value, boolean selected, boolean focused, int row, int column) {
            super.getTableCellRendererComponent(table, value, selected, focused, row, column);         
           setBackground(new java.awt.Color(18,102,153));
            return this;
        }

    }

    private void populateTestTable(){
        DefaultTableModel model = (DefaultTableModel) saniTable.getModel();
        
        model.setRowCount(0);
        for (SanitizationServiceForm saniService : req.getSanitizationServiceFormDirectory().getSanFormList()){          
            Object[] row = new Object[2];
            row[0] = saniService;
            row[1] = saniService.getStatus();
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DoctorScrollPane = new javax.swing.JScrollPane();
        saniTable = new javax.swing.JTable();
        lblDoctorslist1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblEndDate = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        addServicePanel = new javax.swing.JPanel();
        addJButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        sanitizationDate = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        btnNextService = new javax.swing.JButton();
        btnCompleted = new javax.swing.JButton();
        btnDeclined = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        saniTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Date", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        saniTable.setRequestFocusEnabled(false);
        saniTable.setSelectionBackground(new java.awt.Color(235, 227, 126));
        DoctorScrollPane.setViewportView(saniTable);

        lblDoctorslist1.setFont(new java.awt.Font(".SF NS Text", 1, 18)); // NOI18N
        lblDoctorslist1.setText("Sanitization Service");

        jLabel2.setText("Patient's Name:");

        lblName.setText("jLabel4");

        jLabel5.setText("Start Date:");

        lblStartDate.setText("jLabel6");

        jLabel4.setText("End Date:");

        lblEndDate.setText("jLabel6");

        jButton3.setBackground(new java.awt.Color(18, 102, 153));
        jButton3.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton3.setContentAreaFilled(false);
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton3MouseExited(evt);
            }
        });
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblDoctorslist1)
                .addGap(190, 190, 190))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(lblStartDate, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEndDate, javax.swing.GroupLayout.DEFAULT_SIZE, 71, Short.MAX_VALUE)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(DoctorScrollPane)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblDoctorslist1)
                        .addGap(0, 15, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(lblName, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(lblStartDate))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEndDate)))
                .addGap(18, 18, 18)
                .addComponent(DoctorScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(27, 16, 620, 280));

        addServicePanel.setBackground(new java.awt.Color(255, 255, 255));

        addJButton.setBackground(new java.awt.Color(18, 102, 153));
        addJButton.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        addJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/submit.png"))); // NOI18N
        addJButton.setText("Submit");
        addJButton.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        addJButton.setContentAreaFilled(false);
        addJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addJButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addJButtonMouseExited(evt);
            }
        });
        addJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addJButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Date");

        jLabel3.setText("Status:");

        jButton4.setBackground(new java.awt.Color(18, 102, 153));
        jButton4.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        jButton4.setText("Close");
        jButton4.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jButton4.setContentAreaFilled(false);
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jButton4MouseExited(evt);
            }
        });
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addServicePanelLayout = new javax.swing.GroupLayout(addServicePanel);
        addServicePanel.setLayout(addServicePanelLayout);
        addServicePanelLayout.setHorizontalGroup(
            addServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addServicePanelLayout.createSequentialGroup()
                .addGroup(addServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addServicePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sanitizationDate, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addServicePanelLayout.createSequentialGroup()
                        .addGap(213, 213, 213)
                        .addComponent(addJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 72, Short.MAX_VALUE))
        );
        addServicePanelLayout.setVerticalGroup(
            addServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addServicePanelLayout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addGroup(addServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(sanitizationDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(addServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(addServicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addJButton, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );

        add(addServicePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, 620, 150));

        btnNextService.setBackground(new java.awt.Color(18, 102, 153));
        btnNextService.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnNextService.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/add2.png"))); // NOI18N
        btnNextService.setText("Add Next Service");
        btnNextService.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnNextService.setContentAreaFilled(false);
        btnNextService.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNextServiceMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNextServiceMouseExited(evt);
            }
        });
        btnNextService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextServiceActionPerformed(evt);
            }
        });
        add(btnNextService, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 170, 40));

        btnCompleted.setBackground(new java.awt.Color(18, 102, 153));
        btnCompleted.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnCompleted.setText("Completed");
        btnCompleted.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnCompleted.setContentAreaFilled(false);
        btnCompleted.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCompletedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnCompletedMouseExited(evt);
            }
        });
        btnCompleted.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCompletedActionPerformed(evt);
            }
        });
        add(btnCompleted, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 120, 40));

        btnDeclined.setBackground(new java.awt.Color(18, 102, 153));
        btnDeclined.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnDeclined.setText("Declined");
        btnDeclined.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnDeclined.setContentAreaFilled(false);
        btnDeclined.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnDeclinedMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnDeclinedMouseExited(evt);
            }
        });
        btnDeclined.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeclinedActionPerformed(evt);
            }
        });
        add(btnDeclined, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 300, 110, 40));

        btnRemove.setBackground(new java.awt.Color(18, 102, 153));
        btnRemove.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnRemove.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/images/delete2.png"))); // NOI18N
        btnRemove.setText("Remove ");
        btnRemove.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnRemove.setContentAreaFilled(false);
        btnRemove.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnRemoveMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnRemoveMouseExited(evt);
            }
        });
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 120, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void addJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addJButtonActionPerformed

        Date tDate = sanitizationDate.getDate();
        String sanDate = formatter.format(tDate);
        String duration=txtStatus.getText();
        
        SanitizationServiceForm saniService=new SanitizationServiceForm(sanDate,duration);
        req.getSanitizationServiceFormDirectory().addFormList(saniService);
          populateTestTable();
          addServicePanel.setVisible(false);
        
       
        

    }//GEN-LAST:event_addJButtonActionPerformed

    private void btnNextServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextServiceActionPerformed
        // TODO add your handling code here:
        addServicePanel.setVisible(true);
    }//GEN-LAST:event_btnNextServiceActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        addServicePanel.setVisible(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void btnCompletedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCompletedActionPerformed
        // TODO add your handling code here:
        req.setStatus("Completed");
        btnCompleted.setVisible(false);
        btnDeclined.setVisible(false);
        btnNextService.setVisible(false);
        JOptionPane.showMessageDialog(null, "Request completed Successfully");
    }//GEN-LAST:event_btnCompletedActionPerformed

    private void btnDeclinedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeclinedActionPerformed
        // TODO add your handling code here:
        req.setStatus("Declined");
        btnCompleted.setVisible(false);
        btnDeclined.setVisible(false);
        btnNextService.setVisible(false);
        JOptionPane.showMessageDialog(null, "Request declined Successfully");
    }//GEN-LAST:event_btnDeclinedActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:

        int row = saniTable.getSelectedRow();
        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select a row from the table first", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        SanitizationServiceForm saniService=(SanitizationServiceForm)saniTable.getValueAt(row, 0);
        req.getSanitizationServiceFormDirectory().removeFormList(saniService);
        JOptionPane.showMessageDialog(null, "Service Removed Successfully");

        populateTestTable();
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void jButton3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseEntered
        // TODO add your handling code here:
         jButton3.setBackground(new java.awt.Color(18,102,153));
        jButton3.setContentAreaFilled(true);
        jButton3.setFocusPainted(true);
        jButton3.setBorderPainted(false);
         jButton3.setOpaque(true);
    }//GEN-LAST:event_jButton3MouseEntered

    private void jButton3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseExited
        // TODO add your handling code here:
         jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setBorderPainted(true);
    }//GEN-LAST:event_jButton3MouseExited

    private void btnNextServiceMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextServiceMouseEntered
        // TODO add your handling code here:
         btnNextService.setBackground(new java.awt.Color(18,102,153));
        btnNextService.setContentAreaFilled(true);
        btnNextService.setFocusPainted(true);
        btnNextService.setBorderPainted(false);
         btnNextService.setOpaque(true);
    }//GEN-LAST:event_btnNextServiceMouseEntered

    private void btnNextServiceMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNextServiceMouseExited
        // TODO add your handling code here:
         btnNextService.setContentAreaFilled(false);
        btnNextService.setFocusPainted(false);
        btnNextService.setBorderPainted(true);
    }//GEN-LAST:event_btnNextServiceMouseExited

    private void btnCompletedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompletedMouseEntered
        // TODO add your handling code here:
         btnCompleted.setBackground(new java.awt.Color(18,102,153));
        btnCompleted.setContentAreaFilled(true);
        btnCompleted.setFocusPainted(true);
        btnCompleted.setBorderPainted(false);
         btnCompleted.setOpaque(true);
    }//GEN-LAST:event_btnCompletedMouseEntered

    private void btnCompletedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCompletedMouseExited
        // TODO add your handling code here:
         btnCompleted.setContentAreaFilled(false);
        btnCompleted.setFocusPainted(false);
        btnCompleted.setBorderPainted(true);
    }//GEN-LAST:event_btnCompletedMouseExited

    private void btnDeclinedMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeclinedMouseEntered
        // TODO add your handling code here:
         btnDeclined.setBackground(new java.awt.Color(18,102,153));
        btnDeclined.setContentAreaFilled(true);
        btnDeclined.setFocusPainted(true);
        btnDeclined.setBorderPainted(false);
         btnDeclined.setOpaque(true);
    }//GEN-LAST:event_btnDeclinedMouseEntered

    private void btnDeclinedMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeclinedMouseExited
        // TODO add your handling code here:
         btnDeclined.setContentAreaFilled(false);
        btnDeclined.setFocusPainted(false);
        btnDeclined.setBorderPainted(true);
    }//GEN-LAST:event_btnDeclinedMouseExited

    private void btnRemoveMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveMouseEntered
        // TODO add your handling code here:
         btnRemove.setBackground(new java.awt.Color(18,102,153));
        btnRemove.setContentAreaFilled(true);
        btnRemove.setFocusPainted(true);
        btnRemove.setBorderPainted(false);
         btnRemove.setOpaque(true);
    }//GEN-LAST:event_btnRemoveMouseEntered

    private void btnRemoveMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemoveMouseExited
        // TODO add your handling code here:
         btnRemove.setContentAreaFilled(false);
        btnRemove.setFocusPainted(false);
        btnRemove.setBorderPainted(true);
    }//GEN-LAST:event_btnRemoveMouseExited

    private void addJButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addJButtonMouseEntered
        // TODO add your handling code here:
         addJButton.setBackground(new java.awt.Color(18,102,153));
        addJButton.setContentAreaFilled(true);
        addJButton.setFocusPainted(true);
        addJButton.setBorderPainted(false);
         addJButton.setOpaque(true);
    }//GEN-LAST:event_addJButtonMouseEntered

    private void addJButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addJButtonMouseExited
        // TODO add your handling code here:
         addJButton.setContentAreaFilled(false);
        addJButton.setFocusPainted(false);
        addJButton.setBorderPainted(true);
    }//GEN-LAST:event_addJButtonMouseExited

    private void jButton4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseEntered
        // TODO add your handling code here:
         addJButton.setBackground(new java.awt.Color(18,102,153));
        addJButton.setContentAreaFilled(true);
        addJButton.setFocusPainted(true);
        addJButton.setBorderPainted(false);
         addJButton.setOpaque(true);
    }//GEN-LAST:event_jButton4MouseEntered

    private void jButton4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseExited
        // TODO add your handling code here:
         addJButton.setContentAreaFilled(false);
        addJButton.setFocusPainted(false);
        addJButton.setBorderPainted(true);
    }//GEN-LAST:event_jButton4MouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane DoctorScrollPane;
    private javax.swing.JButton addJButton;
    private javax.swing.JPanel addServicePanel;
    private javax.swing.JButton btnCompleted;
    private javax.swing.JButton btnDeclined;
    private javax.swing.JButton btnNextService;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDoctorslist1;
    private javax.swing.JLabel lblEndDate;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JTable saniTable;
    private com.toedter.calendar.JDateChooser sanitizationDate;
    private javax.swing.JTextField txtStatus;
    // End of variables declaration//GEN-END:variables
        public void populateDate(){
            lblName.setText(req.getUser().getName());
            lblStartDate.setText(req.getStartDate());
            lblEndDate.setText(req.getEndDate());
        }
        
        public void toggleButtons(){
            if(req.getStatus().equalsIgnoreCase("completed") || req.getStatus().equalsIgnoreCase("declined") || req.getStatus().equalsIgnoreCase("cancelled")){
                btnCompleted.setVisible(false);
                btnDeclined.setVisible(false);
                btnNextService.setVisible(false);
                btnRemove.setVisible(false);

            }
        }
}
