/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.NurseRole;

import ui.DoctorRole.*;
import ui.UserRole.*;
import ui.TestingEntAdminRole.*;
import ui.FoodSupplyEntAdminRole.*;
import ui.SanitizationEntAdminRole.*;
import ui.PatientSupportEntAdminRole.*;
import ui.HospitalEntAdminRole.*;
import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.Organization.Organization;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JPanel;

/**
 *
 * @author amishagupta
 */

public class NurseWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form HospitalEntAdminWorkAreaJPanel
     */
    JPanel userProcessContainer;
    Enterprise enterprise;
    UserAccount useraccount;
    Organization org;
    EcoSystem system;
    public NurseWorkAreaJPanel(JPanel userProcessContainer, UserAccount useraccount, Organization org, Enterprise enterprise, EcoSystem system) {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.enterprise=enterprise;
        this.useraccount=useraccount;
        this.org=org;
        this.system=system;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnManageProfile = new javax.swing.JButton();
        btnOrderMedicine = new javax.swing.JButton();
        btnBookAmbulance = new javax.swing.JButton();
        btnSanitizationService = new javax.swing.JButton();
        btnAssignedRequests = new javax.swing.JButton();
        btnBookAmbulance1 = new javax.swing.JButton();
        btnBookAmbulance2 = new javax.swing.JButton();
        workAreaJPanel = new javax.swing.JPanel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(235, 227, 126));

        btnManageProfile.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnManageProfile.setText("Manage Profile");
        btnManageProfile.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(74, 126, 203), null, null));
        btnManageProfile.setBorderPainted(false);
        btnManageProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageProfileActionPerformed(evt);
            }
        });

        btnOrderMedicine.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnOrderMedicine.setText("Order Medicine");
        btnOrderMedicine.setBorder(null);
        btnOrderMedicine.setBorderPainted(false);
        btnOrderMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderMedicineActionPerformed(evt);
            }
        });

        btnBookAmbulance.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnBookAmbulance.setText("Book Ambulance");
        btnBookAmbulance.setBorder(null);
        btnBookAmbulance.setBorderPainted(false);
        btnBookAmbulance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookAmbulanceActionPerformed(evt);
            }
        });

        btnSanitizationService.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnSanitizationService.setText("Book Sanitization Service");
        btnSanitizationService.setBorder(null);
        btnSanitizationService.setBorderPainted(false);
        btnSanitizationService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSanitizationServiceActionPerformed(evt);
            }
        });

        btnAssignedRequests.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnAssignedRequests.setText("Assigned Requests");
        btnAssignedRequests.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, new java.awt.Color(74, 126, 203), null, null));
        btnAssignedRequests.setBorderPainted(false);
        btnAssignedRequests.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAssignedRequestsActionPerformed(evt);
            }
        });

        btnBookAmbulance1.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnBookAmbulance1.setText("Book Cab");
        btnBookAmbulance1.setBorder(null);
        btnBookAmbulance1.setBorderPainted(false);
        btnBookAmbulance1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookAmbulance1ActionPerformed(evt);
            }
        });

        btnBookAmbulance2.setFont(new java.awt.Font(".SF NS Text", 1, 14)); // NOI18N
        btnBookAmbulance2.setText("Book Food Service");
        btnBookAmbulance2.setBorder(null);
        btnBookAmbulance2.setBorderPainted(false);
        btnBookAmbulance2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookAmbulance2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnOrderMedicine, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(btnManageProfile, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(btnBookAmbulance, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 238, Short.MAX_VALUE)
                    .addComponent(btnSanitizationService, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(btnAssignedRequests, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(btnBookAmbulance1, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE)
                    .addComponent(btnBookAmbulance2, javax.swing.GroupLayout.DEFAULT_SIZE, 230, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(btnManageProfile, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAssignedRequests, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnOrderMedicine, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBookAmbulance, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSanitizationService, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBookAmbulance1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnBookAmbulance2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(607, Short.MAX_VALUE))
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 880));

        workAreaJPanel.setBackground(new java.awt.Color(74, 122, 193));
        workAreaJPanel.setLayout(new java.awt.CardLayout());
        add(workAreaJPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 0, 1180, 880));
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageProfileActionPerformed
        try {
            // TODO add your handling code here:
            ManageNurseProfile managenurseProfileJPanel=new ManageNurseProfile(workAreaJPanel,enterprise,useraccount,system);
            workAreaJPanel.add("NurseProfileJPanel", managenurseProfileJPanel);
            CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
            layout.next(workAreaJPanel);
        } catch (ParseException ex) {
            Logger.getLogger(NurseWorkAreaJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnManageProfileActionPerformed

    private void btnOrderMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderMedicineActionPerformed
        // TODO add your handling code here:
        RequestMedicineJPanel requestMedicineJPanel=new RequestMedicineJPanel(workAreaJPanel,enterprise,useraccount,system);
        workAreaJPanel.add("MedicineJPanel", requestMedicineJPanel);
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
    }//GEN-LAST:event_btnOrderMedicineActionPerformed

    private void btnBookAmbulanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookAmbulanceActionPerformed
        // TODO add your handling code here:
        BookAmbulanceJPanel bookAmbulanceJPanel=new BookAmbulanceJPanel(workAreaJPanel,enterprise,useraccount,system,org);
        workAreaJPanel.add("bookAmbulanceForPatients", bookAmbulanceJPanel);
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
    }//GEN-LAST:event_btnBookAmbulanceActionPerformed

    private void btnSanitizationServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSanitizationServiceActionPerformed
        // TODO add your handling code here:
        BooKSanitizationJPanel bookSanitization=new BooKSanitizationJPanel(workAreaJPanel,enterprise,useraccount,system,org);
        workAreaJPanel.add("bookSanitizationService", bookSanitization);
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
    }//GEN-LAST:event_btnSanitizationServiceActionPerformed

    private void btnAssignedRequestsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAssignedRequestsActionPerformed
        // TODO add your handling code here:
        NurseAssignedRequest nurseAssignedRequests=new NurseAssignedRequest(workAreaJPanel,enterprise,useraccount,system, org);
        workAreaJPanel.add("viewAllRequestJPanel", nurseAssignedRequests);
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
    }//GEN-LAST:event_btnAssignedRequestsActionPerformed

    private void btnBookAmbulance1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookAmbulance1ActionPerformed
        // TODO add your handling code here:
        BookCabJPanel bookCabPanel=new BookCabJPanel(workAreaJPanel,enterprise,useraccount,system, org);
        workAreaJPanel.add("bookCabForNurse", bookCabPanel);
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
    }//GEN-LAST:event_btnBookAmbulance1ActionPerformed

    private void btnBookAmbulance2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookAmbulance2ActionPerformed
        // TODO add your handling code here:
         BooKFoodJPanel bookFood=new BooKFoodJPanel(workAreaJPanel,enterprise,useraccount,system, org);
        workAreaJPanel.add("bookFoodForPatients", bookFood);
        CardLayout layout = (CardLayout) workAreaJPanel.getLayout();
        layout.next(workAreaJPanel);
    }//GEN-LAST:event_btnBookAmbulance2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAssignedRequests;
    private javax.swing.JButton btnBookAmbulance;
    private javax.swing.JButton btnBookAmbulance1;
    private javax.swing.JButton btnBookAmbulance2;
    private javax.swing.JButton btnManageProfile;
    private javax.swing.JButton btnOrderMedicine;
    private javax.swing.JButton btnSanitizationService;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel workAreaJPanel;
    // End of variables declaration//GEN-END:variables
}
